import Header from '@/components/layout/Header';
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/layout/Sidebar'
import Bottombar from '@/components/layout/Bottombar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Netcico.com || The treasure of information',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={inter.className + "overflow-x-hidden"} >
        <div className="h-screen w-screen bg-white  flex overflow-hidden">
          <Sidebar />
          <div className="w-screen h-full flex flex-col justify-between">
            <Header />
            <main className="h-full flex flex-col overflow-x-hidden  overflow-y-scroll">
              {children}
            </main>
            <Bottombar />
          </div>
        </div>
      </body>
    </html>
  )
}

// lg:w-[91vw] xl:w-[93vw] 2xl:w-[99-vw]  
